pipeline{
    agent any
 tools {
        maven 'maven'
        jdk 'Oracle JDK 11'
    }
    stages{
        stage('checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/nikhilgrg7/DevopsProjectSpring.git']]])
            }
        }
        stage('build'){
            steps{
               bat 'mvn package'
            }
        }
    }
}
