pipeline{
    agent any

    tools {
         maven 'maven'
         jdk 'JDK_1.8'
    }

    stages{
        stage('checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/sreenivas449/java-hello-world-with-maven.git']]])
            }
        }
        stage('build'){
            steps{
               bat 'mvn package'
            }
        }
        stage ('SonarQube Analysis') {
            def munHome = tool name: 'maven-3', type: 'maven'
                withSonarQubeEnv('sq1') {
                 bat "${mvnHome}/bin/mvn sonar: sonar"
                }
        }
}
    }
   
