pipeline{
    agent any

    tools {
         maven 'maven'
         jdk 'JDK_1.8'
    }

    stages{
        stage('checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/nikhilgrg7/DevopsProjectSpring.git']]])
            }
        }
        stage('build'){
            steps{
               bat 'mvn package'
            }
        }
        stage ('SonarQube Analysis') {
        steps{
        withSonarQubeEnv('sonarqube-8.9.2') {
        bat 'mvn sonar:sonar'
                }
        }
        }
}
    }
   
